// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavigateOnServerPagesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigateOnServerPages() {
    driver.get("http://192.168.0.14:10008/");
    driver.manage().window().setSize(new Dimension(878, 748));
    driver.findElement(By.linkText("do simple relative internal links work?")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do general relative links work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do simple absolute links work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do general absolute links work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do URLs with spaces work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do URLs with %20 work")).click();
    driver.findElement(By.linkText("back")).click();
    driver.findElement(By.linkText("do TXT files work")).click();
  }
}
